version: 2.1

orbs:
  node: circleci/node@4.7


jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: install    
      - run:
          command: npm run lint
          name: Run Linter (ESLint)
      - run:
          command: npm run prettier
          name: Formatter (Prettier)
      - run:
          command: npm run test
          name: Run Test (Jest) CI
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .


workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build_and_test
