version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run:
          name: Linter (ESLint)
          command: npm run lint
      - run:
          name: Check code formatting
          command: npm install --save-dev prettier
      - run:
          name: Check code formatting
          command: npm run prettier -c ./src/
      - run:
          name: Test (Jest)
          command: npm run test -- --ci
      - run: npm run build
workflows:
  pull_request:
    jobs:
      - build
