version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Linter (ESLint)
          command: npm run lint
      - run:
          name: Check code formatting
          command: |
            npm install -g prettier            
            npm run prettier
      - run:
          name: Test (Jest)
          command: npm run test -- --ci
      - run: npm run build
workflows:
  pull_request:
    jobs:
      - build
